name: Os varios sabores da TI
description: Espaço para compartilhar minhas experiências por esse mundo de TI.
meta_description: "Os varios sabores da TI, Espaço para compartilhar minhas experiências por esse mundo de TI."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://asferreir.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://asferreir.github.io/'
author:         'Anderson S Ferreira'
